### ISSUE TITLE
Error: Unable to find a match: python3-gobject3-gi

### ISSUE THREAD

**Issue by benjaminbhollon** [mcdope/pam_usb#101]
On running `sudo dnf install libxml2-devel pam-devel libudisks2-devel glib2-devel python3-gobject3-gi` on my Fedora 35 install [as instructed](https://github.com/mcdope/pam_usb/wiki/Install#requirements-fedora-based), I get `Error: Unable to find a match: python3-gobject3-gi`.

Is the package name correct? I expect this is probably just a documentation issue.

Thanks!

**Comment by mcdope** [comment]
Seems it's not :sweat_smile: This part of the docs is still from previous releases by other maintainers, I haven't tested Fedora in a long time. 

If you find the correct one I can update the docs.

**Comment by benjaminbhollon** [comment]
After some initial testing, it seems to install without that dependency included (though it may be something Fedora already had? I'm using a fairly clean install)

By which I mean, the commands exist now. I'll do some more testing to see if I can actually use the program tomorrow; I need to study for my last exam. :)

**Comment by mcdope** [comment]
Possible that it was already installed - maybe under a different name. Without it being installed you should get errors when using `pamusb-conf` at least. Maybe also in the Agent. 

I will test fedora some point in the future. But since this is just a documentation issue it will take some time most likely.

**Comment by mcdope** [comment]
Fixed, the correct name is the one that was given in the `<ul>` - python3-gobject

**Comment by benjaminbhollon** [comment]
Awesome. It does look like that one was already installed on my system, so that would explain why it worked when I just ignored it.
