### ISSUE TITLE
Feature: Check if its possible to unlock keyrings

### ISSUE THREAD

**Issue by mcdope** [mcdope/pam_usb#11]

**Comment by mcdope** [comment]
the manual ways documented in various forum posts don't work on my machine. So I wont document them.

This needs a proper fix (read: keyrings taking pam tokens instead of passed password, see https://gitlab.gnome.org/GNOME/gnome-keyring/-/issues/1)

**Comment by Fuseteam** [comment]
from what i've read the keyring depends on decrypting with and external secret. as a result the secret has to be the same secret that was used to encrypt the keyring in the first place
is it possible to have every device used to authenticate to generate the same key/token? perhaps the keyring password could be changed to that key/token which them gets passed to it on login

**Comment by mcdope** [comment]
Feel free to investigate & submit a PR, but I won't put any more effort into this.

**Comment by Fuseteam** [comment]
guess i'll just post the bugtracker found here for now, I'm not sure how the keyring gets the password from lightdm

**Comment by mcdope** [comment]
As far as I understood it, the PAM module generates a token that used for the encrytption. When you login that token is generated again and passed to "insert your keyring here". But: we cant reproduce that token since we don't know the users password. If we would store it we could take a look at the password pam module, how it generates it token, and reimplement that. But thats a bad idea, even if optional and explicitly requested by the user.

What is really needed imho is proper decoupling of the encryption from the authentication. Somehow the encryption should be based on a system provided token, no matter the authentication module used. But this is nothing we can do, that needs to be done in multiple upstream projects.

**Comment by Fuseteam** [comment]
but encryption is such in nature that it needs a key to decrypt, it that key needs to be the same every time is my understanding at least based on the discussion from https://bugs.launchpad.net/gnome-keyring/+bug/276384
the tldr i got from that is that the token is generated from the user's password since that is bound to be the same every time and as such is suitable to use as encryption key
so technically it not really couple to authentication but rather coupled to the same password, setting the keyring password to blank works around the issue.

**Comment by mcdope** [comment]
Tried that once, didn't worked for me. Have you tried it? 

But also that wouldn't be a solution, at most a workaround to use with agent profiles.

**Comment by Fuseteam** [comment]
Yes i tried it appears to work on my end but yeah true its not a real solution. 
I've been thinking since i posted that... if maybe a separate module would be needed for a real solution one that releases some secret on a successfull authentication

**Comment by mcdope** [comment]
> hey again, i just discovered that we can unlock the keyring insecurely by simply running `echo -n "super_top_secret_password" | gnome-keyring-daemon --daemonize --login` perhaps we can do something with that maybe something crazy like using some property of the usb stick that gets used as the password to decrypt the keyring. that way only that particular stick can be used to decrypt the keyring

To get back on this, after a clean (and I mean REALLY clean, like in not even re-using /home) install on my new PC (:rocket: :smile: ) this is now working for me too. However, after reading the man page of gnome-keyring-daemon I suggest another command: `echo -n "super_top_secret_password" | gnome-keyring-daemon --daemonize --login && gnome-keyring-daemon --start`. According to the manpage `--login` does only the unlock but will not actually start the daemon.

Seems it was caused by multiple keyrings being used on my old install (which again was caused by much earlier versions of pam_usb, pre-me-overtaking).

Guess we could provide at least a shellscript where users can put their password to make this work - if user insists on putting a password in some text file... We could require the script to be in /home and have tight access on the file (like SSH for the key files). Of course this would still expose the password to any root/sudoer...

**Comment by mcdope** [comment]
Yo, @Fuseteam, wanna test? :grin: 

https://www.dropbox.com/s/9a86qmcps7buu7q/libpam-usb_0.8.1_issue11_gnomekeyring_amd64.deb?dl=0 <-- this is a build of my experimental #93 thingy.

To use auto-unlock of your keyring:
* create `~/.keyring_unlock_password`, should contain `UNLOCK_PASSWORD="keyringpassword"`
* `chmod 0666 ~/.keyring_unlock_password`
* create autostart entry for `/usr/bin/pamusb-keyring-unlock-gnome`

Reboot (not sure if relogin is enough, but should be I guess) and enjoy.

**Comment by Fuseteam** [comment]
> > hey again, i just discovered that we can unlock the keyring insecurely by simply running `echo -n "super_top_secret_password" | gnome-keyring-daemon --daemonize --login` perhaps we can do something with that maybe something crazy like using some property of the usb stick that gets used as the password to decrypt the keyring. that way only that particular stick can be used to decrypt the keyring
> 
> To get back on this, after a clean (and I mean REALLY clean, like in not even re-using /home) install on my new PC (rocket smile ) this is now working for me too. However, after reading the man page of gnome-keyring-daemon I suggest another command: `echo -n "super_top_secret_password" | gnome-keyring-daemon --daemonize --login && gnome-keyring-daemon --start`. According to the manpage `--login` does only the unlock but will not actually start the daemon.
> 
> Seems it was caused by multiple keyrings being used on my old install (which again was caused by much earlier versions of pam_usb, pre-me-overtaking).
> 
> Guess we could provide at least a shellscript where users can put their password to make this work - if user insists on putting a password in some text file... We could require the script to be in /home and have tight access on the file (like SSH for the key files). Of course this would still expose the password to any root/sudoer...

ohw cool, that interesting to know, i also got your notif on disqus too! thanks for work on this :)

**Comment by Fuseteam** [comment]
> Yo, @Fuseteam, wanna test? grin
> 
> https://www.dropbox.com/s/9a86qmcps7buu7q/libpam-usb_0.8.1_issue11_gnomekeyring_amd64.deb?dl=0 <-- this is a build of my experimental #93 thingy.
> 
> To use auto-unlock of your keyring see https://github.com/mcdope/pam_usb/wiki/Getting-Started#auto-unlock-your-gnome-keyring
> 
> Reboot (not sure if relogin is enough, but should be I guess) and enjoy.

right-o on it xD

**Comment by Fuseteam** [comment]
seems to work right, awesome thanks :ok_hand: 
i'm currently not able to set the permissions correctly on the authentication device. not sure if it is me or if it is related to how permissions works

**Comment by mcdope** [comment]
Will be caused by the filesystem used, guess it's a non-unix fs like FAT or NTFS. There you can't set octal rights. That's why the default is the home directory. 

On NTFS you could theoretically use ACLs to secure the file, but hf setting that up - no support for that from me ^^

**Comment by Fuseteam** [comment]
Ha! yeah that makes sense. But also mean it doesn't work atm on the authentication device as the rights are incorrect. not sure that should be supported then

**Comment by mcdope** [comment]
You are using rev2, right? The permission check should not be invoked if keyfile is on authdevice and it is FAT or NTFS.

**Comment by mcdope** [comment]
Could you run `findmnt -rn -S UUID=<your-auth-device-uuid> -o TARGET` plz? What does it show?

**Comment by Fuseteam** [comment]
sure, err the uuid is the `<volume_uuid>` property in `/etc/security/pam_usb.conf` right?
it seems to not return anything for me, error code 1

**Comment by Fuseteam** [comment]
> You are using rev2, right? The permission check should not be invoked if keyfile is on authdevice and it is FAT or NTFS.

i think so, i downloaded the one you linked here.....

**Comment by Fuseteam** [comment]
took a closer look i'm not on rev2 yet, downloading now

**Comment by Fuseteam** [comment]
gottem, doesn't seem to work. the findmt command now returns the mounted path of the authentication device

**Comment by mcdope** [comment]
I copied the wrong command 🤦  sorry

Correct one would be `df -T | grep $MOUNTPOINT | awk '{print $2}'` where $MOUNTPOINT is the path returned by the wrongly pasted command / your auth device is mounted on.

I would expect it to report `vfat` or `ntfs` - in which the permission check should be applied. But could be it's bugged.

**Comment by Fuseteam** [comment]
ah lemme try that

**Comment by Fuseteam** [comment]
sorry for the delay yes it returns `vfat`

**Comment by mcdope** [comment]
That sucks, hoped it would be something else >.< 

Then I need to check the switch for the check, must admit have only tested file on device before adding that check. Also never used that syntax to check for strings, keepings scripts /bin/sh compatible is a pain.

**Comment by Fuseteam** [comment]
oof fun >.>

**Comment by mcdope** [comment]
Hm, that's interesting. Actually I can't reproduce this on my system, it works like intended. 

Could you please run `stat /bin/sh`? For me it points to dash.

**Comment by Fuseteam** [comment]
same here, that's odd :thinking:

**Comment by mcdope** [comment]
LOL! Now THATS a plot twist XD

**Comment by Fuseteam** [comment]
ah i mean same as in dash

**Comment by mcdope** [comment]
Then I have no clue why it works here, but not for you :D 

This is maybe asked a bit much, but could you edit `pamusb-keyring-unlock-gnome` at line 34 and replace `fat` with `vfat` ? I don't expect this to fix it, but also I can't think of anything else right now...

**Comment by Fuseteam** [comment]
so replace fat with vfat on line 34? lemme check

**Comment by mcdope** [comment]
Yeah exactly. But I would be surprised if that is the the culprit.

**Comment by Fuseteam** [comment]
weird line 34 didn't have an instance of `fat` but line 19 did so i edited that but didn't make a difference for me :thinking:

**Comment by Fuseteam** [comment]
taking a closer look at the code i notice you use pamusb-check to get the UUID, but uh when i run `pamusb-check \`whoami\`` in the terminal i get no output atm. could it be because i enabled quiet mode?

**Comment by mcdope** [comment]
In line 19 should be the license header. Guess I should provide a new build :sweat_smile: 

And yes, quiet mode could be the cause I guess. If you dont mind, please test it for me ^^

**Comment by Fuseteam** [comment]
already on it, explicitely setting quiet mode to false and running `pamusb-check \`whoami\` 2>&1 | grep "Searching for volume with uuid" | awk '{print $7}' | sed     -e "s/\.//g"` still doesn't return the uuid for me

**Comment by mcdope** [comment]
Try step-debugging it, by removing the pipe'ed cmds

**Comment by Fuseteam** [comment]
already on it, it appears it does return the UUID when debug mode is enabled but not when it is disabled

**Comment by Fuseteam** [comment]
testing to see if it works now with debugging mode enabled

**Comment by mcdope** [comment]
oooooooooooh right. thank you so much. the uuid line is debug output :D so the script needs to run pamusb-check with --debug given, in case user doesnt have it set in config

**Comment by Fuseteam** [comment]
ay no prob xD

**Comment by Fuseteam** [comment]
whoop whoop that works :tada:

**Comment by mcdope** [comment]
this is again such a stupid error... i would really like to have someone reviewing my pull requests except me XD

**Comment by Fuseteam** [comment]
ey no prob happens to the best of us, if it's shell i feel fairly confident now, may i can help with shell stuff xD

**Comment by Fuseteam** [comment]
hmmm one last perhaps obvious thing, the authentication device should be mounted for this to work right?
if yes it might be idea to mention that somewhere

**Comment by mcdope** [comment]
That's kinda obvious, isn't it? 

But is it actually mounted at login already? Guess it's a bit of a bet... Maybe I should just remove support for "on device" again...

**Comment by Fuseteam** [comment]
haha yeah maybe, mine isn't mounted at login. i just realized that. was kinda searching for a way to mount with shell too xD not that i have had luck with it yet hehe

**Comment by Fuseteam** [comment]
ok i'm an idiot its just `sudo mount UUID=<uuid> /path/to/mount` :joy:

**Comment by Fuseteam** [comment]
looks like `sudo mount UUID=<uuid>` might do it regardless of whether it is mounted or not but sudo feels........dirty lol

**Comment by Fuseteam** [comment]
nevermind this is just weird
adding that to the script doesn't help
but running the script (with that added) then running that seems to change something :joy:

**Comment by mcdope** [comment]
Not surprised, env etc.

I will just remove the support for "on device" keyfile.

**Comment by Fuseteam** [comment]
sounds fair enough haha

**Comment by Fuseteam** [comment]
hmm now i'm testing on another computer, i have the feeling killall doesn't actually kill the keyring if it's already running

i tested this as follows:
set the script to start at boot -> keyring is not unlocked
manually kill all instances of the keyring and run the script manually -> keyring is unlocked

here's the output of ps aux|grep keyring immediately after boot:
![image](https://user-images.githubusercontent.com/10421851/141595470-30f163e8-2a55-4d85-b098-a1a238c523fa.png)

**Comment by mcdope** [comment]
Works fine for me here (as long as the keyfile is in ~ :D). 

Maybe the script is launched to early on your system, try adding some sleep either in the script (ugly) or in  the .desktop file for autostart.

**Comment by mcdope** [comment]
Got a new build for you: https://www.dropbox.com/s/izd8sd7t13sixtr/libpam-usb_0.8.1_issue11_gnomekeyring_rev3_amd64.deb?dl=0

This removes onDevice keyfile support and also changes the kill approach to a) use kill instead of killall and b) log the return value for debugging

**Comment by Fuseteam** [comment]
> 
> How do you autostart it anyway, just created a new launcher in "Startprograms"? That's how I did it.

yeah that's how i did it hehe


> Got a new build for you: https://www.dropbox.com/s/izd8sd7t13sixtr/libpam-usb_0.8.1_issue11_gnomekeyring_rev3_amd64.deb?dl=0
> 
> This removes onDevice keyfile support and also changes the kill approach to a) use kill instead of killall and b) log the return value for debugging

awesome thanks i'll test and get back to you

**Comment by Fuseteam** [comment]
yes works thanks :+1:

**Comment by mcdope** [comment]
Remark/Todo for myself: check if we can provide an "installer option" in pamusb-conf.

That option should...
- create the keyfile and chmod it
- create/remove the .desktop file
- disable/enable autostarting gnome-keyring-daemon so we dont need to wait and kill and everything... (todotodo: check if possible)

**Comment by jtsagata** [comment]
Here is an alternative idea:
* Store the password in a file
* Encrypt the file with some device info
* On login decrypt the file, unlock the keyring, and wipe the unencrypted info

**Comment by mcdope** [comment]
Feel free to submit a pull request ;-)
