### ISSUE TITLE
[Packaging] Add PKGBUILD to AUR

### ISSUE THREAD

**Issue by TheScientist101** [mcdope/pam_usb#114]
Hello,
I wanted to add the PKGBUILD in this repo on the AUR. I didn't make the PKGBUILD and wanted to make sure that its ok. I also noticed that the linked AUR package is old and connected to the original repo. 
Thanks.

**Comment by mcdope** [comment]
The PKGBUILD was originally contributed by https://github.com/Fincer, not me. But the whole project is GPL licensed, so as long as that is followed - go ahead. 

It's open source - it doesn't matter if anyone is fine with it :D 

But thanks for asking 👍

**Comment by mcdope** [comment]
Gonna close this since I consider it solved.

**Comment by mcdope** [comment]
@TheScientist101 anything happened on this front? Asking because if not I would try to update the package myself.

**Comment by TheScientist101** [comment]
Sorry, I didn't add it to the AUR because I have not maintained packages before and I have no idea how to maintain a git package. I think it might be better if someone more experienced maintains this package.

**Comment by mcdope** [comment]
Thanks for the feedback. Then I will read some stuff about this and check it myself.

**Comment by mcdope** [comment]
Solved by #151 / @IslandC0der

- https://aur.archlinux.org/packages/pam_usb-git (Builds from `master` branch)
- https://aur.archlinux.org/packages/pam_usb (Builds from configured release tag)
