### ISSUE TITLE
Access Denied on gentoo

### ISSUE THREAD

**Issue by 2403772980ygy** [mcdope/pam_usb#140]
I built pam_usb on gentoo with bspwm, however the pamusb check gave an Access Denied.
```log
❯ pamusb-check --debug erina
* Authentication request for user "erina" (pamusb-check)
[src/local.c:214] Checking whether the caller (pamusb-check) is local or not...
[src/local.c:224] 	Checking pid   8034 (pamusb-check)...
[src/local.c:224] 	Checking pid   6058 (/bin/zsh)...
[src/local.c:224] 	Checking pid   6056 (kitty)...
[src/local.c:224] 	Checking pid      1 (init [3])...
[src/local.c:275] 	Using DISPLAY :0 for utmp search
[src/local.c:049] 	No utmp entry found for tty ":0"
[src/local.c:290] 	Trying to get tty from display server
[src/local.c:298] 		Failed, no result while trying to get TTY from display server
[src/local.c:303] 	Trying to get tty by DISPLAY
[src/local.c:311] 		Failed, no result while searching utmp for display :0 owned by user erina
[src/local.c:318] 	Trying to get tty by loginctl
[src/local.c:177] 		loginctl is not available, skipping
[src/local.c:328] 		Failed, no result while searching utmp for tty (null)
[src/local.c:338] 	Fallback: Using TTY /dev/pts/2 from ttyname() for search
[src/local.c:049] 	No utmp entry found for tty "pts/2"
[src/local.c:346] Couldn't confirm login tty to be neither local or remote - denying.
* Access denied.
```
However when I set the service manually it worked fine.
```log
❯ pamusb-check --debug --service=pamusb-agent erina
* Authentication request for user "erina" (pamusb-agent)
[src/local.c:214] Checking whether the caller (pamusb-agent) is local or not...
[src/local.c:224] 	Checking pid   8070 (pamusb-check)...
[src/local.c:224] 	Checking pid   6058 (/bin/zsh)...
[src/local.c:224] 	Checking pid   6056 (kitty)...
[src/local.c:224] 	Checking pid      1 (init [3])...
[src/local.c:251] Whitelisted request by pamusb-agent detected, assuming local.
[src/local.c:344] No remote access detected, seems to be local request - allowing.
[src/device.c:038] Searching for "NearBrokenKingston" in the hardware database...
* Authentication device "NearBrokenKingston" is connected.
* Performing one time pad verification...
[src/volume.c:097] Searching for volume with uuid 10FB-0C45.
[src/volume.c:121] Found mount points: (null)
[src/volume.c:134] Found volume 10FB-0C45.
[src/volume.c:044] Attempting to mount device /dev/sdb1.
[src/volume.c:056] Mounted device /dev/sdb1 to /run/media/erina/ARCH_202206.
[src/pad.c:290] Loading device pad...
[src/pad.c:299] Loading system pad...
[src/pad.c:313] Pad match.
[src/pad.c:167] Checking whether pads are expired or not...
[src/pad.c:196] Pads were generated 381 seconds ago, not updating.
[src/volume.c:183] Attempting to unmount /dev/sdb1 from /run/media/erina/ARCH_202206.
[src/volume.c:194] Unmount succeeded.
* Access granted.
```
p.s. Don't mind the ARCH_202206 thing, I'm just testing.

I see it is using loginctl to help determine if it is local, however when on gentoo we have openrc & elogind, which also has a loginctl that should work, but the log shows that it is not existent and that appeared like an error.

**Comment by mcdope** [comment]
loginctl is just one of multiple ways to obtain the tty for verification. 

Please post the output of `w` too, so we know what it should find in the first place. But I guess your exotic WM isn't properly registering the session, this was already the case with some other WM.

**Comment by 2403772980ygy** [comment]
Here's the output of w.
```
 18:34:27 up 1 day, 10:39,  1 user,  load average: 0.63, 0.64, 0.45
USER     TTY        LOGIN@   IDLE   JCPU   PCPU WHAT
erina    tty1      Fri07   34:38m  1:05m  0.00s xinit /home/erina/.xinitrc -- /etc/X11/xinit/xserve
```

**Comment by 2403772980ygy** [comment]
I'm also intrigued that why that should make any difference.
I hope that is is not a build issue.

**Comment by mcdope** [comment]
How exactly did you start that session? Looks like login on text console followed by starting X? loginctl way should work in that scenario, if its available (which you said). 

Can you please also provide:
- `which loginctl` - to be sure its available and where
- a working example of calling loginctl on your system

?

This would very likely save me from setting up a VM and recreating the whole scenario.

**Comment by DhruvaSambrani** [comment]
I have the same issue
MANJARO 5.18 - dwm
Works fine when method is explicitly set, as above.

`which loginctl` - `/usr/bin/loginctl`

`w` - 
```
16:08:24 up 37 min,  1 user,  load average: 0.80, 0.54, 0.55
USER     TTY        LOGIN@   IDLE   JCPU   PCPU WHAT
dhruva   tty7      15:46   37:25  42.51s  0.02s /bin/sh /etc/lightdm/Xsession /usr/bin/startdwm
```

`loginctl` -
```
SESSION  UID USER   SEAT  TTY
     24 1000 dhruva seat0 

1 sessions listed.
```

**Comment by DhruvaSambrani** [comment]
Regression caused after v0.8.0

**Comment by mcdope** [comment]
> ```
> SESSION  UID USER   SEAT  TTY
>      24 1000 dhruva seat0 
> 
> 1 sessions listed.
> ```

The TTY column shouldn't be empty, it should contain the session tty (on my system currently i.e tty2 since tty1 has GDM). That's interesting.

But nice that it happens on Manjora, too - since I already have a VM setup for that :D Sadly Virtualbox is yet again not compatible right now with my kernel grml...

> Regression caused after v0.8.0
Most likely, yes. That one had a huge rework of localness check. 

Btw, to circumvent that you can just disable "deny_remote" in the options. Though I wouldn't recommend that if you have sshd or similar running and are leaving the media connected...

**Comment by DhruvaSambrani** [comment]
> The TTY column shouldn't be empty, it should contain the session tty (on my system currently i.e tty2 since tty1 has GDM). That's interesting.

I agree, but I couldn't find any results regarding this when I searched on the web.

> Btw, to circumvent that you can just disable "deny_remote" in the options. Though I wouldn't recommend that if you have sshd or similar running and are leaving the media connected...

I just downgraded to release.

**Comment by mcdope** [comment]
FYI: Oracle finally fixed VirtualBox for current kernels, so I can now properly start to investigate this. Expect a fix, or at least an ETA, next week.

**Comment by mcdope** [comment]
My life had another time planning then me :D But updating my Manjaro VM for testing right now.

**Comment by mcdope** [comment]
@DhruvaSambrani Sneak peak 
![image](https://user-images.githubusercontent.com/3312979/182644037-47969590-f323-47ea-99ff-d7174c432961.png)

Your part of the issue is "fixed". Quotation marks since I still need to clean up, commit etc. But update incoming today.

@2403772980ygy This could *maybe* also fix your part of the issue, but I'm not exactly sure. We will see.

**Comment by mcdope** [comment]
Fix in https://github.com/mcdope/pam_usb/commit/44821800a06091e7b24b0421f5d92a306d553ec1 / branch `issue-140-partB-lightdm-on-non-ubuntu`. Please confirm if its fixes your issue.

**Comment by mcdope** [comment]
Since there was no feedback I consider this done.
