### ISSUE TITLE
"sh: 1: Syntax error: "(" unexpected" in pamusb-check

### ISSUE THREAD

**Issue by MAlfare** [mcdope/pam_usb#186]
### Which version of pam_usb are you running?

Version 0.8.3-1

### Which distribution are you using?

Linux Mint 20.3

### Which login manager and desktop environment are you using?

Cinnamon, lightdm 

### What happened?

alf@Ida ~ $ pamusb-check --debug alf
* Authentication request for user "alf" (pamusb-check)
[src/local.c:227] Checking whether the caller (pamusb-check) is local or not...
[src/local.c:238] 	Checking pid  30578 (pamusb-check)...
[src/local.c:238] 	Checking pid  30464 (bash)...
[src/local.c:238] 	Checking pid  30455 (/usr/libexec/gnome-terminal-server)...
[src/local.c:238] 	Checking pid   1323 (/lib/systemd/systemd)...
[src/local.c:238] 	Checking pid      1 (/sbin/init)...
[src/local.c:296] 	Using DISPLAY :0 for utmp search
[src/local.c:050] 	No utmp entry found for tty ":0"
[src/local.c:312] 	Trying to get tty from display server
[src/local.c:121] 	Determining tty by display server failed (running 'pamusb-check' as user?)
[src/local.c:322] 		Failed, no result while trying to get TTY from display server
[src/local.c:327] 	Trying to get tty by DISPLAY
[src/local.c:335] 		Failed, no result while searching utmp for display :0 owned by user alf
[src/local.c:344] 	Trying to get tty by loginctl
sh: 1: Syntax error: "(" unexpected
[src/local.c:214] 		'loginctl' returned nothing.'
[src/local.c:355] 		Failed, no result while searching utmp for tty (null)
[src/local.c:367] 	Fallback: Using TTY /dev/pts/1 from ttyname() for search
[src/local.c:050] 	No utmp entry found for tty "pts/1"
[src/local.c:378] Couldn't confirm login tty to be neither local or remote - denying.
* Access denied.
1***
alf@Ida ~ $
alf@Ida ~ $ pamusb-check --version alf
Version 0.8.3
1***
alf@Ida ~ $ 

*** die "1" vor dem Prompt ist der Error-Level des vorherigen Befehls

### Output of "pamusb-check --debug `whoami`"

```shell
alf@Ida ~ $ pamusb-check --debug `whoami`
* Authentication request for user "alf" (pamusb-check)
[src/local.c:227] Checking whether the caller (pamusb-check) is local or not...
[src/local.c:238] 	Checking pid  35336 (pamusb-check)...
[src/local.c:238] 	Checking pid  35260 (bash)...
[src/local.c:238] 	Checking pid  30455 (/usr/libexec/gnome-terminal-server)...
[src/local.c:238] 	Checking pid   1323 (/lib/systemd/systemd)...
[src/local.c:238] 	Checking pid      1 (/sbin/init)...
[src/local.c:296] 	Using DISPLAY :0 for utmp search
[src/local.c:050] 	No utmp entry found for tty ":0"
[src/local.c:312] 	Trying to get tty from display server
[src/local.c:121] 	Determining tty by display server failed (running 'pamusb-check' as user?)
[src/local.c:322] 		Failed, no result while trying to get TTY from display server
[src/local.c:327] 	Trying to get tty by DISPLAY
[src/local.c:335] 		Failed, no result while searching utmp for display :0 owned by user alf
[src/local.c:344] 	Trying to get tty by loginctl
sh: 1: Syntax error: "(" unexpected
[src/local.c:214] 		'loginctl' returned nothing.'
[src/local.c:355] 		Failed, no result while searching utmp for tty (null)
[src/local.c:367] 	Fallback: Using TTY /dev/pts/2 from ttyname() for search
[src/local.c:050] 	No utmp entry found for tty "pts/2"
[src/local.c:378] Couldn't confirm login tty to be neither local or remote - denying.
* Access denied.
1
alf@Ida ~ $
```

### Output of "w"

```shell
alf@Ida ~ $ w
 16:46:10 up  3:06,  1 user,  load average: 2,03, 1,59, 1,61
USER     TTY      VON              ANMELD@   UNTÄ   JCPU   PCPU WAS
alf      tty7     :0               15:16    3:06 m  2:13   0.40 s cinnamon-session --session cinnamon

alf@Ida ~ $
```

### Output of "loginctl"

```shell
alf@Ida ~ $ loginctl
SESSION  UID USER SEAT  TTY
     c2 1000 alf  seat0    
     c4 1000 alf  seat0    
     c6 1000 alf  seat0    
     c8 1000 alf  seat0    

4 sessions listed.

alf@Ida ~ $
```

**Comment by mcdope** [comment]
Thanks for reporting, but this is already fixed in master. See #180. 

Just not released as a new version. You can use the nightly build instead.
