### ISSUE TITLE
Couldn't confirm login tty to be neither local or remote - denying (Fedora 37)

### ISSUE THREAD

**Issue by Worf1337** [mcdope/pam_usb#188]
### Which version of pam_usb are you running?

0.8.3

### Which distribution are you using?

Fedora 37

### Which login manager and desktop environment are you using?

Xfce 4.16, lightdm 1.32.0

### What happened?

Attempts to check using xfce4-terminal does not work. The troubleshooting page asks to create an issue about this.

The expected result is a working setup and successful authentication.

### Output of "pamusb-check --debug `whoami`"

```shell
* Authentication request for user "worf" (pamusb-check)
[src/local.c:227] Checking whether the caller (pamusb-check) is local or not...
[src/local.c:238] 	Checking pid 116049 (pamusb-check)...
[src/local.c:238] 	Checking pid  41095 (bash)...
[src/local.c:238] 	Checking pid  27765 (/usr/bin/xfce4-terminal)...
[src/local.c:238] 	Checking pid      1 (/usr/lib/systemd/systemd)...
[src/local.c:296] 	Using DISPLAY :0.0 for utmp search
[src/local.c:301] 	DISPLAY contains screen, truncating...
[src/local.c:050] 	No utmp entry found for tty ":0."
[src/local.c:312] 	Trying to get tty from display server
[src/local.c:322] 		Failed, no result while trying to get TTY from display server
[src/local.c:327] 	Trying to get tty by DISPLAY
[src/local.c:335] 		Failed, no result while searching utmp for display :0. owned by user worf
[src/local.c:344] 	Trying to get tty by loginctl
[src/local.c:214] 		'loginctl' returned nothing.'
[src/local.c:355] 		Failed, no result while searching utmp for tty (null)
[src/local.c:367] 	Fallback: Using TTY /dev/pts/4 from ttyname() for search
[src/local.c:050] 	No utmp entry found for tty "pts/4"
[src/local.c:378] Couldn't confirm login tty to be neither local or remote - denying.
* Access denied.
```

### Output of "w"

```shell
19:04:24 up 18:27,  2 users,  load average: 3.34, 3.22, 2.43
USER     TTY        LOGIN@   IDLE   JCPU   PCPU WHAT
worf     tty1      00:39   18:25m  1:44m  1.89s xfce4-session
worf     pts/1     17:45    4:48   1:12   1:12  /usr/local/bin/cmus
```

### Output of "loginctl"

```shell
SESSION  UID USER SEAT  TTY
      2 1337 worf seat0 

1 sessions listed.
```

**Comment by mcdope** [comment]
Thanks for reporting.

Please try the nightly version, it should be already fixed there (should
finally do a new release 🙈)

Am Sa., 28. Jan. 2023 um 09:05 Uhr schrieb Worf1337 <
***@***.***>:

**Comment by mcdope** [comment]
@Worf1337 I finally set up a fresh VM and tested a bit today. Seems I introduced a bug related to shortening DISPLAY when it contains the screen identifier. 

Seems it's fixed now. See my screenshot, the marked areas, and compare with your screenshot. 
![image](https://user-images.githubusercontent.com/3312979/224490475-a8ef7961-e5a9-4034-8af6-87540de96e17.png)

Please try again with this RPM: https://www.dropbox.com/s/hkiam1pjzf9ga69/pam_usb-0.8.3-1.x86_64.rpm?dl=0

**Comment by mcdope** [comment]
@Worf1337 Any feedback please?

**Comment by Worf1337** [comment]
Whoops, sorry I forgot this issue existed. I'll test this tomorrow. Thanks!

**Comment by Worf1337** [comment]
It worked great, thanks for this.
