### ISSUE TITLE
no login with 'wrong' keyboard mapping

### ISSUE THREAD

**Issue by f1-outsourcing** [mcdope/pam_usb#203]
### Text

I have a newly installed fedora and have to get a bit acquainted with it. This is how I ended up having a different system keyboard. I modified/corrected this in gnome, however because the system was different, I had to login guessing where some characters would be located on the system keyboard. So I had to login in typing keys on a different keyboard location.

Strangely this keyboard setting is also influencing pam_usb. I could remember configuring and being able to login with pam_usb to the gnome session. However when these keyboard layouts were not matching this was not working anymore.
Thus somehow it looks like that pam_usb is depending on the keyboard layout????

**Comment by mcdope** [comment]
No, just no :D For sure it's not keyboard depended. But what could be the case here: the locale causing unexpected output from some invoked external tool.

Hard to say without debug output etc (which is why there is a bug template...)

**Comment by f1-outsourcing** [comment]
Oh good, yes it is a bit weird what I am having, I did not fully check it.
