### ISSUE TITLE
Segfault on sudo request

### ISSUE THREAD

**Issue by mcdope** [mcdope/pam_usb#205]
### Which version of pam_usb are you running?

0.8.3

### Which distribution are you using?

jammy

### Which login manager and desktop environment are you using?

gdm / gnome

### What happened?

Invoked a `sudo` command, hang for quite a while then resulted in segfault. Seems to be related to misc. other crashes.

```
* Authentication request for user "mcdope" (sudo)
[src/local.c:227] Checking whether the caller (sudo) is local or not...
[src/local.c:238] 	Checking pid 293291 (sudo)...
[src/local.c:238] 	Checking pid 251502 (bash)...
[src/local.c:238] 	Checking pid 251481 (gjs)...
[src/local.c:238] 	Checking pid   3907 (/usr/bin/gnome-shell)...
[src/local.c:238] 	Checking pid   3557 (/lib/systemd/systemd)...
[src/local.c:238] 	Checking pid      1 (/sbin/init)...
[src/local.c:296] 	Using DISPLAY :1 for utmp search
[src/local.c:053] 		utmp entry for tty ":1" found
[src/local.c:054] 			utmp->ut_pid: 3748
[src/local.c:055] 			utmp->ut_user: mcdope
[src/local.c:071] 		Checking utmp->ut_addr_v6[0]
[src/local.c:071] 		Checking utmp->ut_addr_v6[1]
[src/local.c:071] 		Checking utmp->ut_addr_v6[2]
[src/local.c:071] 		Checking utmp->ut_addr_v6[3]
[src/local.c:075] 	utmp check successful, request originates from a local source!
[src/local.c:374] No remote access detected, seems to be local request - allowing.

(process:293291): libudisks2-CRITICAL **: 20:51:10.087: udisks_client_get_object_manager: assertion 'UDISKS_IS_CLIENT (client)' failed
Speicherzugriffsfehler (Speicherabzug geschrieben)
```

Happened on each request  (be it sudo or pamusb-check) afterwards again.

### Output of "pamusb-check --debug `whoami`"

```shell
See above, running it yields the same segfault with same output
```

### Output of "w"

```shell
21:02:35 up  5:22,  1 user,  load average: 7,52, 7,42, 7,13
USER     TTY      VON              ANMELD@   UNTÄ   JCPU   PCPU WAS
mcdope   :1       :1               15:40   ?xdm?   1:08 m  0.00 s /usr/libexec/gdm-x-session --run-script env GNOME_SHELL_SESSION_MODE=ubuntu /usr/bin/gnome-session --session=ubuntu
```

### Output of "loginctl"

```shell
SESSION  UID USER   SEAT  TTY 
      2 1000 mcdope seat0 tty2
     c1  126 gdm    seat0 tty1

2 sessions listed.
```

**Comment by KeyofBlueS** [comment]
This happened when upgraded udisks2 to 2.10.0. Reverting to 2.9.4 fixes the problem.

**Comment by mcdope** [comment]
THANKS!

That's a really good clue because other issues seem to be also at least
partially related to udisks. Though its most likely still a f*ckup on my
side.

Am Mo., 10. Juli 2023 um 22:19 Uhr schrieb KeyofBlueS <
***@***.***>:

**Comment by KeyofBlueS** [comment]
Please take a look at https://github.com/storaged-project/udisks/issues/1142, i guess that is the culprit.
I'm on Debian sid. Upgraded again to to 2.10.0-3 and it's working fine now.

**Comment by mcdope** [comment]
Hmm, maybe it is involved - yes. But pretty sure that I put additional mess
in there too :D.





Am Di., 11. Juli 2023 um 12:04 Uhr schrieb KeyofBlueS <
***@***.***>:

**Comment by mcdope** [comment]
Note for myself: just run into it again, should finally take care of it

Note on the note: had issues with SimpleScreenRecorder in the same login session - maybe related? Maybe not...

![grafik](https://github.com/mcdope/pam_usb/assets/3312979/8dda187b-1a41-4f17-a64f-403c627cde53)

**Comment by mcdope** [comment]
@KeyofBlueS in case you still use pam_usb and also still have this happening at times (I hadnt in quite a while): there is a new testbuild which MAY fix it

https://www.dropbox.com/scl/fo/kmll4q7tz3z0agbk4q30x/h?rlkey=da59dbbovgv3ip1qch3hy6lz4&dl=0

**Comment by KeyofBlueS** [comment]
Hey @mcdope, yes I'm still using pam_usb!

After reading our post within this issue, I think the problem was solved, on my side at least, by upgrading udisks2 to 2.10.0-3 (Debian).

Anyway I just tried libpam-usb_0.8.4_amd64.deb and it's working fine.

Please let me know if you need some specific test.

Thanks!

**Comment by mcdope** [comment]
Well, if it really was solved just by udisk for you - glad to hear. I expected it to come back for you, like it did for me sometimes. Never managed to reliable trigger it so testing for it is quite a pain in the .....

I will keep this issue open for three months after release of 0.8.4, just in case, and consider it solved if nobody reports it again :D
