### ISSUE TITLE
typo in wiki install

### ISSUE THREAD

**Issue by m0x3** [mcdope/pam_usb#22]
on this page https://github.com/mcdope/pam_usb/wiki/Install
libpam0g-de two times, but should be libpam0g-de**v**

**Comment by m0x3** [comment]
PS. if you google something like "libpam-usb ubuntu 20.04(focal fossa)", please answer for all, that you have package that work good, it would be nice to find your repo. Thanks!

**Comment by mcdope** [comment]
Fixed, thanks for pointing out.

About searching and answering posts: not gonna happen, to lazy for that. If people look for it, it shouldn't be too hard to find. But feel free to act as "propaganda secretary" :D

**Comment by mcdope** [comment]
Answered on Askubuntu, also asked on Ubuntuusers if they want an updated article which I would happily create. 

But that's all effort I'm gonna put into "advertising". I guess we can assume Linux users are used to googling ;-)
