### ISSUE TITLE
[Packaging] Debian: missing dependency

### ISSUE THREAD

**Issue by mcdope** [mcdope/pam_usb#23]
Seems we are missing a dependency. Invoking pamusb-conf on groovy throws an UDisks related require error

Edit: This was a minimal install btw

![grafik](https://user-images.githubusercontent.com/3312979/101353026-41c96e00-3893-11eb-9991-bb2403132b79.png)

**Comment by KeyofBlueS** [comment]
Hi, the missing dependency in question, on Debian at least, should be gir1.2-udisks-2.0

**Comment by mcdope** [comment]
Thanks, could very well be, but does that also includes the python bindings? 

Will check later, right now I'm supposed to be working :D

**Comment by mcdope** [comment]
Indeed, installing `gir1.2-udisks-2.0` fixes that. Will add it to the depencies.

**Comment by KeyofBlueS** [comment]
Hi, another missing dependency is python3-gi (on a freshly minimal debian install)

**Comment by mcdope** [comment]
Thanks, will be added. Preparing a new release anyway.

**Comment by mcdope** [comment]
My drive for VMs is damn slow, debian is still installing :D 

Do you remember what the issue was exactly? Because I took a look at packages depending on it and didn't found something that's used so I am wondering why it would be needed.

**Comment by mcdope** [comment]
My VM is finally finished, but I couldn't reproduce it with a default install based of the minimal cd (with selected Debian desktop).

![grafik](https://user-images.githubusercontent.com/3312979/103220077-a7070100-491f-11eb-91e9-5424cc3f0ce9.png)

**Comment by KeyofBlueS** [comment]
My debian install was a bare minimal one (without desktop too). Anyhow, without python3-gi, on `pamusb-conf --add-device` or `pamusb-conf --add-user` i get:

```
Traceback (most recent call last):
  File "/usr/bin/pamusb-conf", line 22, in <module>
    gi.require_version('UDisks', '2.0')
AttributeError: module 'gi' has no attribute 'require_version'
```

**Comment by mcdope** [comment]
Hm, but isn't `gir1.2-udisks-2.0` missing a dependency on it then? Would have expected it to be pulled in.

But anyway, will add it.
