### ISSUE TITLE
[CI] Actions: find a way to provide fake usb media for actual testing for working installation

### ISSUE THREAD

**Issue by mcdope** [mcdope/pam_usb#24]
Would be nice if we could provide a fake usb stick or storage card to actually test the setup process and usage...

**Comment by KeyofBlueS** [comment]
I've not tried, but based on my raw searches you need:

- A kernel with Dummy HCD (dummy-hcd) enabled.
You can enable it by adding:
```
CONFIG_USB_DUMMY_HCD=m
```
in kernel config.
Or install it with DKMS:
```
mkdir -p ~/src/dummy-hcd
git clone -b main https://github.com/0prichnik/dummy-hcd.git ~/src/dummy-hcd/master/
cd ~/src/dummy-hcd/master/
make update
make dkms
```

- A kernel with Mass Storage Gadget (g_mass_storage module) enabled:
```
-> Kernel configuration                                                                                                                       
  -> Device Drivers                                                                                                                          
    -> USB support (USB_SUPPORT [=y])                                                                                                       
      -> USB Gadget Support (USB_GADGET [=y])                                                                                                                      
        -> Mass Storage Gadget ( USB_MASS_STORAGE [=m])
```

- Make a disk image, e.g.:
```
fallocate -l 16M Virtual_usb.img
```

- Load dummy-hcd module:
```
sudo modprobe dummy-hcd is_high_speed=1
```

- Load g_mass_storage module:
```
sudo modprobe g_mass_storage file=$HOME/Virtual_usb.img stall=0 removable=y iSerialNumber=1234567890
```

**Comment by KeyofBlueS** [comment]
I confirm that it works fine

**Comment by mcdope** [comment]
Currently creating scripts for it and working on a PR for it. 

Locally it works so far, but not sure loading kernel modules is actually supported in github actions, will see.

**Comment by mcdope** [comment]
Seems the kernel used on the action instances doesn't have USB_GADGET. See https://github.com/mcdope/pam_usb/runs/1526789044?check_suite_focus=true#step:6:46

I don't think this can be solved, since the even if we compile a new kernel - it would require a reboot. This could like be solved by a prebuilt docker image to be used instead of the default stuff. But currently I'm really to lazy for that.

**Comment by KeyofBlueS** [comment]
That's a bad, but expected news

**Comment by mcdope** [comment]
I have one idea left how to do this... a self hosted github runner is not on the table for security reasons since its a public repo and will stay like that (forking the repo would allow thirdparties code execution on the instance by design).

But I could create a limited user/vm on my server, just for checking out the code and running the tests. And that again could be triggered by an SSH or HTTP request from the actions... 

Will look into that somewhere in the near future.

**Comment by mcdope** [comment]
Was quite a pain, but it's working now - in a secure way.

Will add a Wiki page about how to set it up, for forks etc.
