### ISSUE TITLE
lintian: bad-distribution-in-changes-file

### ISSUE THREAD

**Issue by miwie** [mcdope/pam_usb#38]
During build of the deb file (on a _Debian Testing/Bullseye_ system) `lintian libpam-usb_0.7.1_amd64.changes` reports the following error:
`E: libpam-usb changes: bad-distribution-in-changes-file focal`
possibly caused by the line `libpam-usb (0.7.1) focal; urgency=medium`in `debian/changelog`

**Comment by mcdope** [comment]
Fix released as 0.7.2, repo is updated.

https://apt.mcdope.org/libpam-usb_0.7.2_amd64.deb
