### ISSUE TITLE
access denied

### ISSUE THREAD

**Issue by JoshuaMix** [mcdope/pam_usb#58]
So when I first added user to the config file, I checked with pamusb-check and it worked. Then I shut the computer down and later booted it back up. once it was booted I tried to do something with sudo and it wouldn't work. I checked with pamusb-check again and this time it said access denied. I looked around and couldn't find a solution.

**Comment by JoshuaMix** [comment]
I apologize in advance if this is me being an idiot.

**Comment by mcdope** [comment]
What does `pamusb-check --debug <yourusername>` show?

**Comment by JoshuaMix** [comment]
this is what i got for my main user
* Authentication request for user "oswald" (pamusb-check)
[src/local.c:033] Checking whether the caller is local or not...
[src/local.c:039]     Checking pid  16813 (pamusb-check)...
[src/local.c:039]     Checking pid  16633 (bash)...
[src/local.c:039]     Checking pid  16625 (mate-terminal)...
[src/local.c:039]     Checking pid   2034 (mate-panel)...
[src/local.c:039]     Checking pid   1762 (mate-session)...
[src/local.c:039]     Checking pid   1708 (lightdm)...
[src/local.c:039]     Checking pid    970 (/usr/sbin/lightdm)...
[src/local.c:039]     Checking pid      1 (/sbin/init)...
[src/local.c:048] No remote daemons found in parent process list, seems to be local request - allowing.
[src/device.c:038] Searching for "PasswordsAreWhack" in the hardware database...
* Authentication device "PasswordsAreWhack" is connected.
* Performing one time pad verification...
[src/volume.c:097] Searching for volume with uuid 486B-5113.
[src/volume.c:121] Found mount points: /media/oswald/USB_RAPTOR
[src/volume.c:134] Found volume 486B-5113.
[src/volume.c:158] Volume 486B-5113 is already mounted.
[src/pad.c:256] Loading device pad...
[src/pad.c:258] Loading system pad...
* Pad checking failed!
* Access denied.

this is what happens for root

* Authentication request for user "root" (pamusb-check)
[src/local.c:033] Checking whether the caller is local or not...
[src/local.c:039]     Checking pid  16825 (pamusb-check)...
[src/local.c:039]     Checking pid  16633 (bash)...
[src/local.c:039]     Checking pid  16625 (mate-terminal)...
[src/local.c:039]     Checking pid   2034 (mate-panel)...
[src/local.c:039]     Checking pid   1762 (mate-session)...
[src/local.c:039]     Checking pid   1708 (lightdm)...
[src/local.c:039]     Checking pid    970 (/usr/sbin/lightdm)...
[src/local.c:039]     Checking pid      1 (/sbin/init)...
[src/local.c:048] No remote daemons found in parent process list, seems to be local request - allowing.
[src/device.c:038] Searching for "PasswordsAreWhack" in the hardware database...
* Authentication device "PasswordsAreWhack" is connected.
* Performing one time pad verification...
[src/volume.c:097] Searching for volume with uuid 486B-5113.
[src/volume.c:121] Found mount points: /media/oswald/USB_RAPTOR
[src/volume.c:134] Found volume 486B-5113.
[src/volume.c:158] Volume 486B-5113 is already mounted.
[src/pad.c:090] Directory /root/.pamusb does not exist, creating one.
[src/pad.c:093] Unable to create directory /root/.pamusb: Permission denied
[src/pad.c:153] Checking whether pads are expired or not...
[src/pad.c:090] Directory /root/.pamusb does not exist, creating one.
[src/pad.c:093] Unable to create directory /root/.pamusb: Permission denied
[src/pad.c:156] Unable to open system pad, pads must be generated.
* Regenerating new pads...
[src/pad.c:123] Protecting pad file...
[src/pad.c:133] Unable to change owner of the pad: Operation not permitted
[src/pad.c:090] Directory /root/.pamusb does not exist, creating one.
[src/pad.c:093] Unable to create directory /root/.pamusb: Permission denied
* Unable to update pads.
* Access granted.

**Comment by mcdope** [comment]
The interesting part in your case is `Pad checking failed!`.

This is a case of pad mismatch. The pad is the file making sure that you can't simply connect a media with same serial and name etc to circumvent pamusb. Seems there are some permission issues either in your homedir on `.pamusb` or on the media itself. I've had these issues in example with an almost baked SD-Card or with hw-write-protection (like these switches on MicroSD to SD Adapters).,

You can fix this by just deleting the pad file from homedir and device and there will be a new one created. (which btw is why should encrypt your home partition while using pamusb - but one should do so in any case :P)

However, the "[src/pad.c:093] Unable to create directory /root/.pamusb: Permission denied" is wierd - as root you shouldn't have any issues creating directories. Same for "[src/pad.c:133] Unable to change owner of the pad: Operation not permitted". Either your system is enforcing some strange policies, /root is writeprotected or something like that. Out of curiosity, what does `sudo pamusb-check <yourusername>` show?

**Comment by JoshuaMix** [comment]
I get the same error. however, whenever i run sudo pamusb-check/debug root, I get access denied. Not sure if that helps.

**Comment by mcdope** [comment]
That's highly unusual, I can't imagine what's going on there. Which distro in which version are you using?

What I would recommend: remove `.pamusb` from all user directories and `/root`. Then `purge` (not just `remove`!) the package and install it again. After that start again with configuration. 

Also: there is no (valid) reason to use pamusb for root, you should never login as root and pamusb on sudo works without that. But nonetheless it should work as root, else there is something blocking around - most likely some policy framework like SELinux or so.

**Comment by mcdope** [comment]
Small addition: also make sure to remove the pamusb directory from your media

**Comment by JoshuaMix** [comment]
I'm using Linux Mint 20.1

**Comment by mcdope** [comment]
I will download an image and setup a VM to test with it, but pretty sure it's caused by your specific setup - can't imagine Mint messed up the default permissions so much.

**Comment by mcdope** [comment]
Just tried with a freshly installed stock Mint 20.1, all updates installed and it works exactly like expected / perfectly. 

So what it is for you, it is an issue of your setup. Follow the "start over" steps given above or if that doesn't help fix your system.
