### ISSUE TITLE
Installation on Manjaro

### ISSUE THREAD

**Issue by eda-abec** [mcdope/pam_usb#98]
Hello,
I have managed to install this on my Manjaro, but it took some digging to figure out how. So I'll share it here for anyone having same problem, or maybe you can fix it in the Makefile (sorry, I don't have that much time).

The package is not available in Manjaro repositories, so I built it manually. No problem here.

The problem was, `pam_usb.so` was installed (by `make install`) into `/lib64/security/security/pam_usb.so`, whereas it should be placed into `/lib64/security/pam_usb.so`.

Pam did not tell me the file was not found (because I included it as `sufficient`?) and it took me some time, so hopefully this helps others on Manjaro to spare that time.

**Comment by mcdope** [comment]
Without having checked it, guess caused by my fix for #94. 

Will check

**Comment by mcdope** [comment]
Can you please checkout branch issue-98-fix-non-debian-libdir and confirm this fixes it?

**Comment by eda-abec** [comment]
I tried deinstalling and installing again with the new Makefile and it works. Thanks :)

**Comment by LageTs** [comment]
Also on Manjaro (KDE). I just installed yesterday, the libs seem to be placed correct (`/lib64/security/pam_usb.so` and `/lib/security/pam_usb.so`) and `pamusb-check` works. But when I try to add pamusb to `/etc/pam.d/system-auth` it still just uses password auth.

My system-auth (just added one line, others were default):
```
auth       required                    pam_faillock.so      preauth
auth       sufficient                  pam_usb.so
auth       [success=2 default=ignore]  pam_unix.so          try_first_pass nullok
-auth      [success=1 default=ignore]  pam_systemd_home.so
auth       [default=die]               pam_faillock.so      authfail
auth       optional                    pam_permit.so
auth       required                    pam_env.so
auth       required                    pam_faillock.so      authsucc
```

I don't get any pam related errors in journalctl.

**Comment by mcdope** [comment]
Define "it" - console login? graphical login? if graphical which loginmanager? sudo? 

What is `pamusb-conf --debug username` outputting?
